// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"unicode/utf8"
)

const (
	ErrEmptyValue = "empty"
	ErrMaxLength  = "len"
	ErrWrongValue = "value"
)

func (u User) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(u.Login) > 64 {
		errors[Columns.User.Login] = ErrMaxLength
	}

	if utf8.RuneCountInString(u.Password) > 64 {
		errors[Columns.User.Password] = ErrMaxLength
	}

	if utf8.RuneCountInString(u.AuthKey) > 32 {
		errors[Columns.User.AuthKey] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (vf VfsFile) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(vf.Title) > 255 {
		errors[Columns.VfsFile.Title] = ErrMaxLength
	}

	if utf8.RuneCountInString(vf.Path) > 255 {
		errors[Columns.VfsFile.Path] = ErrMaxLength
	}

	if utf8.RuneCountInString(vf.MimeType) > 255 {
		errors[Columns.VfsFile.MimeType] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (vf VfsFolder) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(vf.Title) > 255 {
		errors[Columns.VfsFolder.Title] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (c Candidate) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(c.Name) > 80 {
		errors[Columns.Candidate.Name] = ErrMaxLength
	}

	if utf8.RuneCountInString(c.Handle) > 40 {
		errors[Columns.Candidate.Handle] = ErrMaxLength
	}

	if utf8.RuneCountInString(c.Login) > 64 {
		errors[Columns.Candidate.Login] = ErrMaxLength
	}

	if utf8.RuneCountInString(c.Password) > 64 {
		errors[Columns.Candidate.Password] = ErrMaxLength
	}

	if utf8.RuneCountInString(c.AuthKey) > 32 {
		errors[Columns.Candidate.AuthKey] = ErrMaxLength
	}

	if utf8.RuneCountInString(c.City) > 128 {
		errors[Columns.Candidate.City] = ErrMaxLength
	}

	if utf8.RuneCountInString(c.AvatarColor) > 16 {
		errors[Columns.Candidate.AvatarColor] = ErrMaxLength
	}

	if utf8.RuneCountInString(c.Initials) > 3 {
		errors[Columns.Candidate.Initials] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (s Stage) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(s.Alias) > 64 {
		errors[Columns.Stage.Alias] = ErrMaxLength
	}

	if utf8.RuneCountInString(s.Title) > 255 {
		errors[Columns.Stage.Title] = ErrMaxLength
	}

	if utf8.RuneCountInString(s.ShortTitle) > 64 {
		errors[Columns.Stage.ShortTitle] = ErrMaxLength
	}

	return errors, len(errors) == 0
}
