// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"
)

var Columns = struct {
	User struct {
		ID, CreatedAt, Login, Password, AuthKey, LastActivityAt, StatusID string
	}
	VfsFile struct {
		ID, FolderID, Title, Path, Params, IsFavorite, MimeType, FileSize, FileExists, CreatedAt, StatusID string

		Folder string
	}
	VfsFolder struct {
		ID, ParentFolderID, Title, IsFavorite, CreatedAt, StatusID string

		ParentFolder string
	}
	Candidate struct {
		ID, Name, Handle, City, Age, Bio, AvatarColor, Initials, AvatarUrl, Strengths, Weaknesses, CurrentStageID, CreatedAt, UpdatedAt, CompletedAt, StatusID string

		CurrentStage string
	}
	StageScore struct {
		ID, CandidateID, StageID, Score, ScoredAt string

		Candidate, Stage string
	}
	Stage struct {
		ID, Alias, Order, Title, ShortTitle, Description, MaxScore, StatusID string
	}
}{
	User: struct {
		ID, CreatedAt, Login, Password, AuthKey, LastActivityAt, StatusID string
	}{
		ID:             "userId",
		CreatedAt:      "createdAt",
		Login:          "login",
		Password:       "password",
		AuthKey:        "authKey",
		LastActivityAt: "lastActivityAt",
		StatusID:       "statusId",
	},
	VfsFile: struct {
		ID, FolderID, Title, Path, Params, IsFavorite, MimeType, FileSize, FileExists, CreatedAt, StatusID string

		Folder string
	}{
		ID:         "fileId",
		FolderID:   "folderId",
		Title:      "title",
		Path:       "path",
		Params:     "params",
		IsFavorite: "isFavorite",
		MimeType:   "mimeType",
		FileSize:   "fileSize",
		FileExists: "fileExists",
		CreatedAt:  "createdAt",
		StatusID:   "statusId",

		Folder: "Folder",
	},
	VfsFolder: struct {
		ID, ParentFolderID, Title, IsFavorite, CreatedAt, StatusID string

		ParentFolder string
	}{
		ID:             "folderId",
		ParentFolderID: "parentFolderId",
		Title:          "title",
		IsFavorite:     "isFavorite",
		CreatedAt:      "createdAt",
		StatusID:       "statusId",

		ParentFolder: "ParentFolder",
	},
	Candidate: struct {
		ID, Name, Handle, City, Age, Bio, AvatarColor, Initials, AvatarUrl, Strengths, Weaknesses, CurrentStageID, CreatedAt, UpdatedAt, CompletedAt, StatusID string

		CurrentStage string
	}{
		ID:             "candidateId",
		Name:           "name",
		Handle:         "handle",
		City:           "city",
		Age:            "age",
		Bio:            "bio",
		AvatarColor:    "avatarColor",
		Initials:       "initials",
		AvatarUrl:      "avatarUrl",
		Strengths:      "strengths",
		Weaknesses:     "weaknesses",
		CurrentStageID: "currentStageId",
		CreatedAt:      "createdAt",
		UpdatedAt:      "updatedAt",
		CompletedAt:    "completedAt",
		StatusID:       "statusId",

		CurrentStage: "CurrentStage",
	},
	StageScore: struct {
		ID, CandidateID, StageID, Score, ScoredAt string

		Candidate, Stage string
	}{
		ID:          "scoreId",
		CandidateID: "candidateId",
		StageID:     "stageId",
		Score:       "score",
		ScoredAt:    "scoredAt",

		Candidate: "Candidate",
		Stage:     "Stage",
	},
	Stage: struct {
		ID, Alias, Order, Title, ShortTitle, Description, MaxScore, StatusID string
	}{
		ID:          "stageId",
		Alias:       "alias",
		Order:       "order",
		Title:       "title",
		ShortTitle:  "shortTitle",
		Description: "description",
		MaxScore:    "maxScore",
		StatusID:    "statusId",
	},
}

var Tables = struct {
	User struct {
		Name, Alias string
	}
	VfsFile struct {
		Name, Alias string
	}
	VfsFolder struct {
		Name, Alias string
	}
	Candidate struct {
		Name, Alias string
	}
	StageScore struct {
		Name, Alias string
	}
	Stage struct {
		Name, Alias string
	}
}{
	User: struct {
		Name, Alias string
	}{
		Name:  "users",
		Alias: "t",
	},
	VfsFile: struct {
		Name, Alias string
	}{
		Name:  "vfsFiles",
		Alias: "t",
	},
	VfsFolder: struct {
		Name, Alias string
	}{
		Name:  "vfsFolders",
		Alias: "t",
	},
	Candidate: struct {
		Name, Alias string
	}{
		Name:  "candidates",
		Alias: "t",
	},
	StageScore: struct {
		Name, Alias string
	}{
		Name:  "stageScores",
		Alias: "t",
	},
	Stage: struct {
		Name, Alias string
	}{
		Name:  "stages",
		Alias: "t",
	},
}

type User struct {
	tableName struct{} `pg:"users,alias:t,discard_unknown_columns"`

	ID             int        `pg:"userId,pk"`
	CreatedAt      time.Time  `pg:"createdAt,use_zero"`
	Login          string     `pg:"login,use_zero"`
	Password       string     `pg:"password,use_zero"`
	AuthKey        string     `pg:"authKey,use_zero"`
	LastActivityAt *time.Time `pg:"lastActivityAt"`
	StatusID       int        `pg:"statusId,use_zero"`
}

type VfsFile struct {
	tableName struct{} `pg:"vfsFiles,alias:t,discard_unknown_columns"`

	ID         int       `pg:"fileId,pk"`
	FolderID   int       `pg:"folderId,use_zero"`
	Title      string    `pg:"title,use_zero"`
	Path       string    `pg:"path,use_zero"`
	Params     *string   `pg:"params"`
	IsFavorite *bool     `pg:"isFavorite"`
	MimeType   string    `pg:"mimeType,use_zero"`
	FileSize   *int      `pg:"fileSize"`
	FileExists bool      `pg:"fileExists,use_zero"`
	CreatedAt  time.Time `pg:"createdAt,use_zero"`
	StatusID   int       `pg:"statusId,use_zero"`

	Folder *VfsFolder `pg:"fk:folderId,rel:has-one"`
}

type VfsFolder struct {
	tableName struct{} `pg:"vfsFolders,alias:t,discard_unknown_columns"`

	ID             int       `pg:"folderId,pk"`
	ParentFolderID *int      `pg:"parentFolderId"`
	Title          string    `pg:"title,use_zero"`
	IsFavorite     *bool     `pg:"isFavorite"`
	CreatedAt      time.Time `pg:"createdAt,use_zero"`
	StatusID       int       `pg:"statusId,use_zero"`

	ParentFolder *VfsFolder `pg:"fk:parentFolderId,rel:has-one"`
}

type Candidate struct {
	tableName struct{} `pg:"candidates,alias:t,discard_unknown_columns"`

	ID             int        `pg:"candidateId,pk"`
	Name           string     `pg:"name,use_zero"`
	Handle         string     `pg:"handle,use_zero"`
	City           string     `pg:"city,use_zero"`
	Age            *int       `pg:"age"`
	Bio            string     `pg:"bio,use_zero"`
	AvatarColor    string     `pg:"avatarColor,use_zero"`
	Initials       string     `pg:"initials,use_zero"`
	AvatarUrl      *string    `pg:"avatarUrl"`
	Strengths      []string   `pg:"strengths,array,use_zero"`
	Weaknesses     []string   `pg:"weaknesses,array,use_zero"`
	CurrentStageID int        `pg:"currentStageId,use_zero"`
	CreatedAt      time.Time  `pg:"createdAt,use_zero"`
	UpdatedAt      time.Time  `pg:"updatedAt,use_zero"`
	CompletedAt    *time.Time `pg:"completedAt"`
	StatusID       int        `pg:"statusId,use_zero"`

	CurrentStage *Stage `pg:"fk:currentStageId,rel:has-one"`
}

type StageScore struct {
	tableName struct{} `pg:"stageScores,alias:t,discard_unknown_columns"`

	ID          int       `pg:"scoreId,pk"`
	CandidateID int       `pg:"candidateId,use_zero"`
	StageID     int       `pg:"stageId,use_zero"`
	Score       int       `pg:"score,use_zero"`
	ScoredAt    time.Time `pg:"scoredAt,use_zero"`

	Candidate *Candidate `pg:"fk:candidateId,rel:has-one"`
	Stage     *Stage     `pg:"fk:stageId,rel:has-one"`
}

type Stage struct {
	tableName struct{} `pg:"stages,alias:t,discard_unknown_columns"`

	ID          int    `pg:"stageId,pk"`
	Alias       string `pg:"alias,use_zero"`
	Order       int    `pg:"order,use_zero"`
	Title       string `pg:"title,use_zero"`
	ShortTitle  string `pg:"shortTitle,use_zero"`
	Description string `pg:"description,use_zero"`
	MaxScore    int    `pg:"maxScore,use_zero"`
	StatusID    int    `pg:"statusId,use_zero"`
}
