// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"
)

var Columns = struct {
	User struct {
		ID, CreatedAt, Login, Password, AuthKey, LastActivityAt, StatusID string
	}
	VfsFile struct {
		ID, FolderID, Title, Path, Params, IsFavorite, MimeType, FileSize, FileExists, CreatedAt, StatusID string

		Folder string
	}
	VfsFolder struct {
		ID, ParentFolderID, Title, IsFavorite, CreatedAt, StatusID string

		ParentFolder string
	}
	Candidate struct {
		ID, Name, Handle, Login, Password, AuthKey, LastActivityAt, City, Age, Bio, AvatarColor, Initials, AvatarUrl, Strengths, Weaknesses, CurrentStageID, CreatedAt, UpdatedAt, CompletedAt, StatusID string

		CurrentStage string
	}
	CandidateStage struct {
		ID, CandidateID, StageID, Link, Score, ScoredAt, ScoredBy, Deadline, IsReady, SetReadyAt, Retries, CreatedAt string

		Candidate, Stage string
	}
	Stage struct {
		ID, Alias, Order, Title, ShortTitle, Description, MaxScore, DeadlineDays, StatusID string
	}
	CandidateMaterial struct {
		ID, CandidateID, MaterialID, ReadAt, Score, ScoredAt, ScoredBy, Notes, CreatedAt string

		Candidate, Material string
	}
	Material struct {
		ID, Title, Type, Url, Description, MaxScore, Order, StatusID, CreatedAt, UpdatedAt string
	}
}{
	User: struct {
		ID, CreatedAt, Login, Password, AuthKey, LastActivityAt, StatusID string
	}{
		ID:             "userId",
		CreatedAt:      "createdAt",
		Login:          "login",
		Password:       "password",
		AuthKey:        "authKey",
		LastActivityAt: "lastActivityAt",
		StatusID:       "statusId",
	},
	VfsFile: struct {
		ID, FolderID, Title, Path, Params, IsFavorite, MimeType, FileSize, FileExists, CreatedAt, StatusID string

		Folder string
	}{
		ID:         "fileId",
		FolderID:   "folderId",
		Title:      "title",
		Path:       "path",
		Params:     "params",
		IsFavorite: "isFavorite",
		MimeType:   "mimeType",
		FileSize:   "fileSize",
		FileExists: "fileExists",
		CreatedAt:  "createdAt",
		StatusID:   "statusId",

		Folder: "Folder",
	},
	VfsFolder: struct {
		ID, ParentFolderID, Title, IsFavorite, CreatedAt, StatusID string

		ParentFolder string
	}{
		ID:             "folderId",
		ParentFolderID: "parentFolderId",
		Title:          "title",
		IsFavorite:     "isFavorite",
		CreatedAt:      "createdAt",
		StatusID:       "statusId",

		ParentFolder: "ParentFolder",
	},
	Candidate: struct {
		ID, Name, Handle, Login, Password, AuthKey, LastActivityAt, City, Age, Bio, AvatarColor, Initials, AvatarUrl, Strengths, Weaknesses, CurrentStageID, CreatedAt, UpdatedAt, CompletedAt, StatusID string

		CurrentStage string
	}{
		ID:             "candidateId",
		Name:           "name",
		Handle:         "handle",
		Login:          "login",
		Password:       "password",
		AuthKey:        "authKey",
		LastActivityAt: "lastActivityAt",
		City:           "city",
		Age:            "age",
		Bio:            "bio",
		AvatarColor:    "avatarColor",
		Initials:       "initials",
		AvatarUrl:      "avatarUrl",
		Strengths:      "strengths",
		Weaknesses:     "weaknesses",
		CurrentStageID: "currentStageId",
		CreatedAt:      "createdAt",
		UpdatedAt:      "updatedAt",
		CompletedAt:    "completedAt",
		StatusID:       "statusId",

		CurrentStage: "CurrentStage",
	},
	CandidateStage: struct {
		ID, CandidateID, StageID, Link, Score, ScoredAt, ScoredBy, Deadline, IsReady, SetReadyAt, Retries, CreatedAt string

		Candidate, Stage string
	}{
		ID:          "candidateStageId",
		CandidateID: "candidateId",
		StageID:     "stageId",
		Link:        "link",
		Score:       "score",
		ScoredAt:    "scoredAt",
		ScoredBy:    "scoredBy",
		Deadline:    "deadline",
		IsReady:     "isReady",
		SetReadyAt:  "setReadyAt",
		Retries:     "retries",
		CreatedAt:   "createdAt",

		Candidate: "Candidate",
		Stage:     "Stage",
	},
	Stage: struct {
		ID, Alias, Order, Title, ShortTitle, Description, MaxScore, DeadlineDays, StatusID string
	}{
		ID:           "stageId",
		Alias:        "alias",
		Order:        "order",
		Title:        "title",
		ShortTitle:   "shortTitle",
		Description:  "description",
		MaxScore:     "maxScore",
		DeadlineDays: "deadlineDays",
		StatusID:     "statusId",
	},
	CandidateMaterial: struct {
		ID, CandidateID, MaterialID, ReadAt, Score, ScoredAt, ScoredBy, Notes, CreatedAt string

		Candidate, Material string
	}{
		ID:          "candidateMaterialId",
		CandidateID: "candidateId",
		MaterialID:  "materialId",
		ReadAt:      "readAt",
		Score:       "score",
		ScoredAt:    "scoredAt",
		ScoredBy:    "scoredBy",
		Notes:       "notes",
		CreatedAt:   "createdAt",

		Candidate: "Candidate",
		Material:  "Material",
	},
	Material: struct {
		ID, Title, Type, Url, Description, MaxScore, Order, StatusID, CreatedAt, UpdatedAt string
	}{
		ID:          "materialId",
		Title:       "title",
		Type:        "type",
		Url:         "url",
		Description: "description",
		MaxScore:    "maxScore",
		Order:       "order",
		StatusID:    "statusId",
		CreatedAt:   "createdAt",
		UpdatedAt:   "updatedAt",
	},
}

var Tables = struct {
	User struct {
		Name, Alias string
	}
	VfsFile struct {
		Name, Alias string
	}
	VfsFolder struct {
		Name, Alias string
	}
	Candidate struct {
		Name, Alias string
	}
	CandidateStage struct {
		Name, Alias string
	}
	Stage struct {
		Name, Alias string
	}
	CandidateMaterial struct {
		Name, Alias string
	}
	Material struct {
		Name, Alias string
	}
}{
	User: struct {
		Name, Alias string
	}{
		Name:  "users",
		Alias: "t",
	},
	VfsFile: struct {
		Name, Alias string
	}{
		Name:  "vfsFiles",
		Alias: "t",
	},
	VfsFolder: struct {
		Name, Alias string
	}{
		Name:  "vfsFolders",
		Alias: "t",
	},
	Candidate: struct {
		Name, Alias string
	}{
		Name:  "candidates",
		Alias: "t",
	},
	CandidateStage: struct {
		Name, Alias string
	}{
		Name:  "candidateStages",
		Alias: "t",
	},
	Stage: struct {
		Name, Alias string
	}{
		Name:  "stages",
		Alias: "t",
	},
	CandidateMaterial: struct {
		Name, Alias string
	}{
		Name:  "candidateMaterials",
		Alias: "t",
	},
	Material: struct {
		Name, Alias string
	}{
		Name:  "materials",
		Alias: "t",
	},
}

type User struct {
	tableName struct{} `pg:"users,alias:t,discard_unknown_columns"`

	ID             int        `pg:"userId,pk"`
	CreatedAt      time.Time  `pg:"createdAt,use_zero"`
	Login          string     `pg:"login,use_zero"`
	Password       string     `pg:"password,use_zero"`
	AuthKey        string     `pg:"authKey,use_zero"`
	LastActivityAt *time.Time `pg:"lastActivityAt"`
	StatusID       int        `pg:"statusId,use_zero"`
}

type VfsFile struct {
	tableName struct{} `pg:"vfsFiles,alias:t,discard_unknown_columns"`

	ID         int       `pg:"fileId,pk"`
	FolderID   int       `pg:"folderId,use_zero"`
	Title      string    `pg:"title,use_zero"`
	Path       string    `pg:"path,use_zero"`
	Params     *string   `pg:"params"`
	IsFavorite *bool     `pg:"isFavorite"`
	MimeType   string    `pg:"mimeType,use_zero"`
	FileSize   *int      `pg:"fileSize"`
	FileExists bool      `pg:"fileExists,use_zero"`
	CreatedAt  time.Time `pg:"createdAt,use_zero"`
	StatusID   int       `pg:"statusId,use_zero"`

	Folder *VfsFolder `pg:"fk:folderId,rel:has-one"`
}

type VfsFolder struct {
	tableName struct{} `pg:"vfsFolders,alias:t,discard_unknown_columns"`

	ID             int       `pg:"folderId,pk"`
	ParentFolderID *int      `pg:"parentFolderId"`
	Title          string    `pg:"title,use_zero"`
	IsFavorite     *bool     `pg:"isFavorite"`
	CreatedAt      time.Time `pg:"createdAt,use_zero"`
	StatusID       int       `pg:"statusId,use_zero"`

	ParentFolder *VfsFolder `pg:"fk:parentFolderId,rel:has-one"`
}

type Candidate struct {
	tableName struct{} `pg:"candidates,alias:t,discard_unknown_columns"`

	ID             int        `pg:"candidateId,pk"`
	Name           string     `pg:"name,use_zero"`
	Handle         string     `pg:"handle,use_zero"`
	Login          string     `pg:"login,use_zero"`
	Password       string     `pg:"password,use_zero"`
	AuthKey        string     `pg:"authKey,use_zero"`
	LastActivityAt *time.Time `pg:"lastActivityAt"`
	City           string     `pg:"city,use_zero"`
	Age            *int       `pg:"age"`
	Bio            string     `pg:"bio,use_zero"`
	AvatarColor    string     `pg:"avatarColor,use_zero"`
	Initials       string     `pg:"initials,use_zero"`
	AvatarUrl      *string    `pg:"avatarUrl"`
	Strengths      []string   `pg:"strengths,array,use_zero"`
	Weaknesses     []string   `pg:"weaknesses,array,use_zero"`
	CurrentStageID int        `pg:"currentStageId,use_zero"`
	CreatedAt      time.Time  `pg:"createdAt,use_zero"`
	UpdatedAt      time.Time  `pg:"updatedAt,use_zero"`
	CompletedAt    *time.Time `pg:"completedAt"`
	StatusID       int        `pg:"statusId,use_zero"`

	CurrentStage *Stage `pg:"fk:currentStageId,rel:has-one"`
}

type CandidateStage struct {
	tableName struct{} `pg:"candidateStages,alias:t,discard_unknown_columns"`

	ID          int        `pg:"candidateStageId,pk"`
	CandidateID int        `pg:"candidateId,use_zero"`
	StageID     int        `pg:"stageId,use_zero"`
	Link        *string    `pg:"link"`
	Score       *int       `pg:"score"`
	ScoredAt    *time.Time `pg:"scoredAt"`
	ScoredBy    *int       `pg:"scoredBy"`
	Deadline    *time.Time `pg:"deadline"`
	IsReady     bool       `pg:"isReady,use_zero"`
	SetReadyAt  *time.Time `pg:"setReadyAt"`
	Retries     int        `pg:"retries,use_zero"`
	CreatedAt   time.Time  `pg:"createdAt,use_zero"`

	Candidate *Candidate `pg:"fk:candidateId,rel:has-one"`
	Stage     *Stage     `pg:"fk:stageId,rel:has-one"`
}

type Stage struct {
	tableName struct{} `pg:"stages,alias:t,discard_unknown_columns"`

	ID           int    `pg:"stageId,pk"`
	Alias        string `pg:"alias,use_zero"`
	Order        int    `pg:"order,use_zero"`
	Title        string `pg:"title,use_zero"`
	ShortTitle   string `pg:"shortTitle,use_zero"`
	Description  string `pg:"description,use_zero"`
	MaxScore     int    `pg:"maxScore,use_zero"`
	DeadlineDays int    `pg:"deadlineDays,use_zero"`
	StatusID     int    `pg:"statusId,use_zero"`
}

type CandidateMaterial struct {
	tableName struct{} `pg:"candidateMaterials,alias:t,discard_unknown_columns"`

	ID          int        `pg:"candidateMaterialId,pk"`
	CandidateID int        `pg:"candidateId,use_zero"`
	MaterialID  int        `pg:"materialId,use_zero"`
	ReadAt      *time.Time `pg:"readAt"`
	Score       *int       `pg:"score"`
	ScoredAt    *time.Time `pg:"scoredAt"`
	ScoredBy    *int       `pg:"scoredBy"`
	Notes       *string    `pg:"notes"`
	CreatedAt   time.Time  `pg:"createdAt,use_zero"`

	Candidate *Candidate `pg:"fk:candidateId,rel:has-one"`
	Material  *Material  `pg:"fk:materialId,rel:has-one"`
}

type Material struct {
	tableName struct{} `pg:"materials,alias:t,discard_unknown_columns"`

	ID          int       `pg:"materialId,pk"`
	Title       string    `pg:"title,use_zero"`
	Type        string    `pg:"type,use_zero"`
	Url         string    `pg:"url,use_zero"`
	Description string    `pg:"description,use_zero"`
	MaxScore    int       `pg:"maxScore,use_zero"`
	Order       int       `pg:"order,use_zero"`
	StatusID    int       `pg:"statusId,use_zero"`
	CreatedAt   time.Time `pg:"createdAt,use_zero"`
	UpdatedAt   time.Time `pg:"updatedAt,use_zero"`
}
