// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"

	"github.com/go-pg/pg/v10"
	"github.com/go-pg/pg/v10/orm"
)

const condition = "?.? = ?"

// base filters
type applier func(query *orm.Query) (*orm.Query, error)

type search struct {
	appliers []applier
}

func (s *search) apply(query *orm.Query) {
	for _, applier := range s.appliers {
		query.Apply(applier)
	}
}

func (s *search) where(query *orm.Query, table, field string, value interface{}) {
	query.Where(condition, pg.Ident(table), pg.Ident(field), value)
}

func (s *search) WithApply(a applier) {
	if s.appliers == nil {
		s.appliers = []applier{}
	}
	s.appliers = append(s.appliers, a)
}

func (s *search) With(condition string, params ...interface{}) {
	s.WithApply(func(query *orm.Query) (*orm.Query, error) {
		return query.Where(condition, params...), nil
	})
}

// Searcher is interface for every generated filter
type Searcher interface {
	Apply(query *orm.Query) *orm.Query
	Q() applier

	With(condition string, params ...interface{})
	WithApply(a applier)
}

type UserSearch struct {
	search

	ID                 *int
	CreatedAt          *time.Time
	Login              *string
	Password           *string
	AuthKey            *string
	LastActivityAt     *time.Time
	StatusID           *int
	IDs                []int
	NotID              *int
	LoginILike         *string
	PasswordILike      *string
	AuthKeyILike       *string
	LastActivityAtFrom *time.Time
	LastActivityAtTo   *time.Time
}

func (us *UserSearch) Apply(query *orm.Query) *orm.Query {
	if us == nil {
		return query
	}
	if us.ID != nil {
		us.where(query, Tables.User.Alias, Columns.User.ID, us.ID)
	}
	if us.CreatedAt != nil {
		us.where(query, Tables.User.Alias, Columns.User.CreatedAt, us.CreatedAt)
	}
	if us.Login != nil {
		us.where(query, Tables.User.Alias, Columns.User.Login, us.Login)
	}
	if us.Password != nil {
		us.where(query, Tables.User.Alias, Columns.User.Password, us.Password)
	}
	if us.AuthKey != nil {
		us.where(query, Tables.User.Alias, Columns.User.AuthKey, us.AuthKey)
	}
	if us.LastActivityAt != nil {
		us.where(query, Tables.User.Alias, Columns.User.LastActivityAt, us.LastActivityAt)
	}
	if us.StatusID != nil {
		us.where(query, Tables.User.Alias, Columns.User.StatusID, us.StatusID)
	}
	if len(us.IDs) > 0 {
		Filter{Columns.User.ID, us.IDs, SearchTypeArray, false}.Apply(query)
	}
	if us.NotID != nil {
		Filter{Columns.User.ID, *us.NotID, SearchTypeEquals, true}.Apply(query)
	}
	if us.LoginILike != nil {
		Filter{Columns.User.Login, *us.LoginILike, SearchTypeILike, false}.Apply(query)
	}
	if us.PasswordILike != nil {
		Filter{Columns.User.Password, *us.PasswordILike, SearchTypeILike, false}.Apply(query)
	}
	if us.AuthKeyILike != nil {
		Filter{Columns.User.AuthKey, *us.AuthKeyILike, SearchTypeILike, false}.Apply(query)
	}
	if us.LastActivityAtFrom != nil {
		Filter{Columns.User.LastActivityAt, *us.LastActivityAtFrom, SearchTypeGE, false}.Apply(query)
	}
	if us.LastActivityAtTo != nil {
		Filter{Columns.User.LastActivityAt, *us.LastActivityAtTo, SearchTypeLE, false}.Apply(query)
	}

	us.apply(query)

	return query
}

func (us *UserSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if us == nil {
			return query, nil
		}
		return us.Apply(query), nil
	}
}

type VfsFileSearch struct {
	search

	ID            *int
	FolderID      *int
	Title         *string
	Path          *string
	Params        *string
	IsFavorite    *bool
	MimeType      *string
	FileSize      *int
	FileExists    *bool
	CreatedAt     *time.Time
	StatusID      *int
	IDs           []int
	TitleILike    *string
	PathILike     *string
	ParamsILike   *string
	MimeTypeILike *string
}

func (vfs *VfsFileSearch) Apply(query *orm.Query) *orm.Query {
	if vfs == nil {
		return query
	}
	if vfs.ID != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.ID, vfs.ID)
	}
	if vfs.FolderID != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.FolderID, vfs.FolderID)
	}
	if vfs.Title != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.Title, vfs.Title)
	}
	if vfs.Path != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.Path, vfs.Path)
	}
	if vfs.Params != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.Params, vfs.Params)
	}
	if vfs.IsFavorite != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.IsFavorite, vfs.IsFavorite)
	}
	if vfs.MimeType != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.MimeType, vfs.MimeType)
	}
	if vfs.FileSize != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.FileSize, vfs.FileSize)
	}
	if vfs.FileExists != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.FileExists, vfs.FileExists)
	}
	if vfs.CreatedAt != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.CreatedAt, vfs.CreatedAt)
	}
	if vfs.StatusID != nil {
		vfs.where(query, Tables.VfsFile.Alias, Columns.VfsFile.StatusID, vfs.StatusID)
	}
	if len(vfs.IDs) > 0 {
		Filter{Columns.VfsFile.ID, vfs.IDs, SearchTypeArray, false}.Apply(query)
	}
	if vfs.TitleILike != nil {
		Filter{Columns.VfsFile.Title, *vfs.TitleILike, SearchTypeILike, false}.Apply(query)
	}
	if vfs.PathILike != nil {
		Filter{Columns.VfsFile.Path, *vfs.PathILike, SearchTypeILike, false}.Apply(query)
	}
	if vfs.ParamsILike != nil {
		Filter{Columns.VfsFile.Params, *vfs.ParamsILike, SearchTypeILike, false}.Apply(query)
	}
	if vfs.MimeTypeILike != nil {
		Filter{Columns.VfsFile.MimeType, *vfs.MimeTypeILike, SearchTypeILike, false}.Apply(query)
	}

	vfs.apply(query)

	return query
}

func (vfs *VfsFileSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if vfs == nil {
			return query, nil
		}
		return vfs.Apply(query), nil
	}
}

type VfsFolderSearch struct {
	search

	ID             *int
	ParentFolderID *int
	Title          *string
	IsFavorite     *bool
	CreatedAt      *time.Time
	StatusID       *int
	IDs            []int
	TitleILike     *string
}

func (vfs *VfsFolderSearch) Apply(query *orm.Query) *orm.Query {
	if vfs == nil {
		return query
	}
	if vfs.ID != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.ID, vfs.ID)
	}
	if vfs.ParentFolderID != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.ParentFolderID, vfs.ParentFolderID)
	}
	if vfs.Title != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.Title, vfs.Title)
	}
	if vfs.IsFavorite != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.IsFavorite, vfs.IsFavorite)
	}
	if vfs.CreatedAt != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.CreatedAt, vfs.CreatedAt)
	}
	if vfs.StatusID != nil {
		vfs.where(query, Tables.VfsFolder.Alias, Columns.VfsFolder.StatusID, vfs.StatusID)
	}
	if len(vfs.IDs) > 0 {
		Filter{Columns.VfsFolder.ID, vfs.IDs, SearchTypeArray, false}.Apply(query)
	}
	if vfs.TitleILike != nil {
		Filter{Columns.VfsFolder.Title, *vfs.TitleILike, SearchTypeILike, false}.Apply(query)
	}

	vfs.apply(query)

	return query
}

func (vfs *VfsFolderSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if vfs == nil {
			return query, nil
		}
		return vfs.Apply(query), nil
	}
}

type CandidateSearch struct {
	search

	ID               *int
	Name             *string
	Handle           *string
	City             *string
	Age              *int
	Bio              *string
	AvatarColor      *string
	Initials         *string
	AvatarUrl        *string
	CurrentStageID   *int
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
	CompletedAt      *time.Time
	StatusID         *int
	IDs              []int
	NameILike        *string
	HandleILike      *string
	CityILike        *string
	BioILike         *string
	AvatarColorILike *string
	InitialsILike    *string
	AvatarUrlILike   *string
}

func (cs *CandidateSearch) Apply(query *orm.Query) *orm.Query {
	if cs == nil {
		return query
	}
	if cs.ID != nil {
		cs.where(query, Tables.Candidate.Alias, Columns.Candidate.ID, cs.ID)
	}
	if cs.Name != nil {
		cs.where(query, Tables.Candidate.Alias, Columns.Candidate.Name, cs.Name)
	}
	if cs.Handle != nil {
		cs.where(query, Tables.Candidate.Alias, Columns.Candidate.Handle, cs.Handle)
	}
	if cs.City != nil {
		cs.where(query, Tables.Candidate.Alias, Columns.Candidate.City, cs.City)
	}
	if cs.Age != nil {
		cs.where(query, Tables.Candidate.Alias, Columns.Candidate.Age, cs.Age)
	}
	if cs.Bio != nil {
		cs.where(query, Tables.Candidate.Alias, Columns.Candidate.Bio, cs.Bio)
	}
	if cs.AvatarColor != nil {
		cs.where(query, Tables.Candidate.Alias, Columns.Candidate.AvatarColor, cs.AvatarColor)
	}
	if cs.Initials != nil {
		cs.where(query, Tables.Candidate.Alias, Columns.Candidate.Initials, cs.Initials)
	}
	if cs.AvatarUrl != nil {
		cs.where(query, Tables.Candidate.Alias, Columns.Candidate.AvatarUrl, cs.AvatarUrl)
	}
	if cs.CurrentStageID != nil {
		cs.where(query, Tables.Candidate.Alias, Columns.Candidate.CurrentStageID, cs.CurrentStageID)
	}
	if cs.CreatedAt != nil {
		cs.where(query, Tables.Candidate.Alias, Columns.Candidate.CreatedAt, cs.CreatedAt)
	}
	if cs.UpdatedAt != nil {
		cs.where(query, Tables.Candidate.Alias, Columns.Candidate.UpdatedAt, cs.UpdatedAt)
	}
	if cs.CompletedAt != nil {
		cs.where(query, Tables.Candidate.Alias, Columns.Candidate.CompletedAt, cs.CompletedAt)
	}
	if cs.StatusID != nil {
		cs.where(query, Tables.Candidate.Alias, Columns.Candidate.StatusID, cs.StatusID)
	}
	if len(cs.IDs) > 0 {
		Filter{Columns.Candidate.ID, cs.IDs, SearchTypeArray, false}.Apply(query)
	}
	if cs.NameILike != nil {
		Filter{Columns.Candidate.Name, *cs.NameILike, SearchTypeILike, false}.Apply(query)
	}
	if cs.HandleILike != nil {
		Filter{Columns.Candidate.Handle, *cs.HandleILike, SearchTypeILike, false}.Apply(query)
	}
	if cs.CityILike != nil {
		Filter{Columns.Candidate.City, *cs.CityILike, SearchTypeILike, false}.Apply(query)
	}
	if cs.BioILike != nil {
		Filter{Columns.Candidate.Bio, *cs.BioILike, SearchTypeILike, false}.Apply(query)
	}
	if cs.AvatarColorILike != nil {
		Filter{Columns.Candidate.AvatarColor, *cs.AvatarColorILike, SearchTypeILike, false}.Apply(query)
	}
	if cs.InitialsILike != nil {
		Filter{Columns.Candidate.Initials, *cs.InitialsILike, SearchTypeILike, false}.Apply(query)
	}
	if cs.AvatarUrlILike != nil {
		Filter{Columns.Candidate.AvatarUrl, *cs.AvatarUrlILike, SearchTypeILike, false}.Apply(query)
	}

	cs.apply(query)

	return query
}

func (cs *CandidateSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if cs == nil {
			return query, nil
		}
		return cs.Apply(query), nil
	}
}

type StageScoreSearch struct {
	search

	ID          *int
	CandidateID *int
	StageID     *int
	Score       *int
	ScoredAt    *time.Time
	IDs         []int
}

func (sss *StageScoreSearch) Apply(query *orm.Query) *orm.Query {
	if sss == nil {
		return query
	}
	if sss.ID != nil {
		sss.where(query, Tables.StageScore.Alias, Columns.StageScore.ID, sss.ID)
	}
	if sss.CandidateID != nil {
		sss.where(query, Tables.StageScore.Alias, Columns.StageScore.CandidateID, sss.CandidateID)
	}
	if sss.StageID != nil {
		sss.where(query, Tables.StageScore.Alias, Columns.StageScore.StageID, sss.StageID)
	}
	if sss.Score != nil {
		sss.where(query, Tables.StageScore.Alias, Columns.StageScore.Score, sss.Score)
	}
	if sss.ScoredAt != nil {
		sss.where(query, Tables.StageScore.Alias, Columns.StageScore.ScoredAt, sss.ScoredAt)
	}
	if len(sss.IDs) > 0 {
		Filter{Columns.StageScore.ID, sss.IDs, SearchTypeArray, false}.Apply(query)
	}

	sss.apply(query)

	return query
}

func (sss *StageScoreSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if sss == nil {
			return query, nil
		}
		return sss.Apply(query), nil
	}
}

type StageSearch struct {
	search

	ID               *int
	Alias            *string
	Order            *int
	Title            *string
	ShortTitle       *string
	Description      *string
	MaxScore         *int
	StatusID         *int
	IDs              []int
	NotID            *int
	TitleILike       *string
	ShortTitleILike  *string
	DescriptionILike *string
}

func (ss *StageSearch) Apply(query *orm.Query) *orm.Query {
	if ss == nil {
		return query
	}
	if ss.ID != nil {
		ss.where(query, Tables.Stage.Alias, Columns.Stage.ID, ss.ID)
	}
	if ss.Alias != nil {
		ss.where(query, Tables.Stage.Alias, Columns.Stage.Alias, ss.Alias)
	}
	if ss.Order != nil {
		ss.where(query, Tables.Stage.Alias, Columns.Stage.Order, ss.Order)
	}
	if ss.Title != nil {
		ss.where(query, Tables.Stage.Alias, Columns.Stage.Title, ss.Title)
	}
	if ss.ShortTitle != nil {
		ss.where(query, Tables.Stage.Alias, Columns.Stage.ShortTitle, ss.ShortTitle)
	}
	if ss.Description != nil {
		ss.where(query, Tables.Stage.Alias, Columns.Stage.Description, ss.Description)
	}
	if ss.MaxScore != nil {
		ss.where(query, Tables.Stage.Alias, Columns.Stage.MaxScore, ss.MaxScore)
	}
	if ss.StatusID != nil {
		ss.where(query, Tables.Stage.Alias, Columns.Stage.StatusID, ss.StatusID)
	}
	if len(ss.IDs) > 0 {
		Filter{Columns.Stage.ID, ss.IDs, SearchTypeArray, false}.Apply(query)
	}
	if ss.NotID != nil {
		Filter{Columns.Stage.ID, *ss.NotID, SearchTypeEquals, true}.Apply(query)
	}
	if ss.TitleILike != nil {
		Filter{Columns.Stage.Title, *ss.TitleILike, SearchTypeILike, false}.Apply(query)
	}
	if ss.ShortTitleILike != nil {
		Filter{Columns.Stage.ShortTitle, *ss.ShortTitleILike, SearchTypeILike, false}.Apply(query)
	}
	if ss.DescriptionILike != nil {
		Filter{Columns.Stage.Description, *ss.DescriptionILike, SearchTypeILike, false}.Apply(query)
	}

	ss.apply(query)

	return query
}

func (ss *StageSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if ss == nil {
			return query, nil
		}
		return ss.Apply(query), nil
	}
}
