// Code generated by zenrpc v2.3.1; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	CandidateService struct{ Get, GetByID, Add, Update, Delete, Advance, Rate, Rollback, Kanban string }
	DashboardService struct{ Summary string }
	StageService     struct{ Get, GetByID, Add, Update, Delete, Reorder string }
}{
	CandidateService: struct{ Get, GetByID, Add, Update, Delete, Advance, Rate, Rollback, Kanban string }{
		Get:      "get",
		GetByID:  "getbyid",
		Add:      "add",
		Update:   "update",
		Delete:   "delete",
		Advance:  "advance",
		Rate:     "rate",
		Rollback: "rollback",
		Kanban:   "kanban",
	},
	DashboardService: struct{ Summary string }{
		Summary: "summary",
	},
	StageService: struct{ Get, GetByID, Add, Update, Delete, Reorder string }{
		Get:     "get",
		GetByID: "getbyid",
		Add:     "add",
		Update:  "update",
		Delete:  "delete",
		Reorder: "reorder",
	},
}

func (CandidateService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Get": {
				Description: `Get returns candidate list with aggregates, sorted by sortBy.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "sortBy",
						Description: `CandidateSort`,
						Type:        smd.Object,
						TypeName:    "CandidateSort",
						Properties:  smd.PropertyList{},
					},
				},
				Returns: smd.JSONSchema{
					Description: `[]CandidateSummary`,
					Type:        smd.Array,
					TypeName:    "[]CandidateSummary",
					Items: map[string]string{
						"$ref": "#/definitions/CandidateSummary",
					},
					Definitions: map[string]smd.Definition{
						"CandidateSummary": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "handle",
									Type: smd.String,
								},
								{
									Name: "city",
									Type: smd.String,
								},
								{
									Name:     "age",
									Optional: true,
									Type:     smd.Integer,
								},
								{
									Name: "avatarColor",
									Type: smd.String,
								},
								{
									Name: "initials",
									Type: smd.String,
								},
								{
									Name:     "avatarUrl",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name: "strengths",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "weaknesses",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name:     "currentStage",
									Optional: true,
									Ref:      "#/definitions/Stage",
									Type:     smd.Object,
								},
								{
									Name: "totalPoints",
									Type: smd.Integer,
								},
								{
									Name: "maxPoints",
									Type: smd.Integer,
								},
								{
									Name: "completedStages",
									Type: smd.Integer,
								},
								{
									Name: "stageCount",
									Type: smd.Integer,
								},
								{
									Name:     "completedAt",
									Optional: true,
									Type:     smd.String,
								},
							},
						},
						"Stage": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "alias",
									Type: smd.String,
								},
								{
									Name: "order",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "shortTitle",
									Type: smd.String,
								},
								{
									Name: "description",
									Type: smd.String,
								},
								{
									Name: "maxScore",
									Type: smd.Integer,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					500: "Internal Error",
				},
			},
			"GetByID": {
				Description: `GetByID returns full candidate detail with stage history.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "id",
						Description: `int`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `CandidateDetail`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "CandidateDetail",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "name",
							Type: smd.String,
						},
						{
							Name: "handle",
							Type: smd.String,
						},
						{
							Name: "city",
							Type: smd.String,
						},
						{
							Name:     "age",
							Optional: true,
							Type:     smd.Integer,
						},
						{
							Name: "avatarColor",
							Type: smd.String,
						},
						{
							Name: "initials",
							Type: smd.String,
						},
						{
							Name:     "avatarUrl",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "strengths",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "weaknesses",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name:     "currentStage",
							Optional: true,
							Ref:      "#/definitions/Stage",
							Type:     smd.Object,
						},
						{
							Name: "totalPoints",
							Type: smd.Integer,
						},
						{
							Name: "maxPoints",
							Type: smd.Integer,
						},
						{
							Name: "completedStages",
							Type: smd.Integer,
						},
						{
							Name: "stageCount",
							Type: smd.Integer,
						},
						{
							Name:     "completedAt",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "bio",
							Type: smd.String,
						},
						{
							Name: "history",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/CandidateStageHistory",
							},
						},
					},
					Definitions: map[string]smd.Definition{
						"Stage": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "alias",
									Type: smd.String,
								},
								{
									Name: "order",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "shortTitle",
									Type: smd.String,
								},
								{
									Name: "description",
									Type: smd.String,
								},
								{
									Name: "maxScore",
									Type: smd.Integer,
								},
							},
						},
						"CandidateStageHistory": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "stageId",
									Type: smd.Integer,
								},
								{
									Name:     "stage",
									Optional: true,
									Ref:      "#/definitions/Stage",
									Type:     smd.Object,
								},
								{
									Name: "status",
									Type: smd.String,
								},
								{
									Name:     "score",
									Optional: true,
									Type:     smd.Integer,
								},
								{
									Name: "maxScore",
									Type: smd.Integer,
								},
								{
									Name:     "scoredAt",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name:     "scoreId",
									Optional: true,
									Type:     smd.Integer,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					404: "Not Found",
					500: "Internal Error",
				},
			},
			"Add": {
				Description: `Add creates a new candidate.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "candidate",
						Description: `Candidate`,
						Type:        smd.Object,
						TypeName:    "Candidate",
						Properties: smd.PropertyList{
							{
								Name: "id",
								Type: smd.Integer,
							},
							{
								Name: "name",
								Type: smd.String,
							},
							{
								Name: "handle",
								Type: smd.String,
							},
							{
								Name: "city",
								Type: smd.String,
							},
							{
								Name:     "age",
								Optional: true,
								Type:     smd.Integer,
							},
							{
								Name: "bio",
								Type: smd.String,
							},
							{
								Name: "avatarColor",
								Type: smd.String,
							},
							{
								Name: "initials",
								Type: smd.String,
							},
							{
								Name:     "avatarUrl",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name: "strengths",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "weaknesses",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "currentStageId",
								Type: smd.Integer,
							},
							{
								Name: "createdAt",
								Type: smd.String,
							},
							{
								Name: "updatedAt",
								Type: smd.String,
							},
							{
								Name:     "completedAt",
								Optional: true,
								Type:     smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `Candidate`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "Candidate",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "name",
							Type: smd.String,
						},
						{
							Name: "handle",
							Type: smd.String,
						},
						{
							Name: "city",
							Type: smd.String,
						},
						{
							Name:     "age",
							Optional: true,
							Type:     smd.Integer,
						},
						{
							Name: "bio",
							Type: smd.String,
						},
						{
							Name: "avatarColor",
							Type: smd.String,
						},
						{
							Name: "initials",
							Type: smd.String,
						},
						{
							Name:     "avatarUrl",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "strengths",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "weaknesses",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "currentStageId",
							Type: smd.Integer,
						},
						{
							Name: "createdAt",
							Type: smd.String,
						},
						{
							Name: "updatedAt",
							Type: smd.String,
						},
						{
							Name:     "completedAt",
							Optional: true,
							Type:     smd.String,
						},
					},
				},
				Errors: map[int]string{
					400: "Validation Error",
					500: "Internal Error",
				},
			},
			"Update": {
				Description: `Update changes candidate's basic fields. Use Advance/Rollback for stage progression.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "candidate",
						Description: `Candidate`,
						Type:        smd.Object,
						TypeName:    "Candidate",
						Properties: smd.PropertyList{
							{
								Name: "id",
								Type: smd.Integer,
							},
							{
								Name: "name",
								Type: smd.String,
							},
							{
								Name: "handle",
								Type: smd.String,
							},
							{
								Name: "city",
								Type: smd.String,
							},
							{
								Name:     "age",
								Optional: true,
								Type:     smd.Integer,
							},
							{
								Name: "bio",
								Type: smd.String,
							},
							{
								Name: "avatarColor",
								Type: smd.String,
							},
							{
								Name: "initials",
								Type: smd.String,
							},
							{
								Name:     "avatarUrl",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name: "strengths",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "weaknesses",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "currentStageId",
								Type: smd.Integer,
							},
							{
								Name: "createdAt",
								Type: smd.String,
							},
							{
								Name: "updatedAt",
								Type: smd.String,
							},
							{
								Name:     "completedAt",
								Optional: true,
								Type:     smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
				Errors: map[int]string{
					404: "Not Found",
					400: "Validation Error",
					500: "Internal Error",
				},
			},
			"Delete": {
				Description: `Delete soft-deletes a candidate.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "id",
						Description: `int`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
				Errors: map[int]string{
					404: "Not Found",
					500: "Internal Error",
				},
			},
			"Advance": {
				Description: `Advance scores the candidate for their current stage and moves them to the next one.
If current stage is the last, completedAt is set instead.`,
				Parameters: []smd.JSONSchema{
					{
						Name: "candidateID",
						Type: smd.Integer,
					},
					{
						Name:        "score",
						Description: `int`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `AdvanceResult`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "AdvanceResult",
					Properties: smd.PropertyList{
						{
							Name:     "candidate",
							Optional: true,
							Ref:      "#/definitions/Candidate",
							Type:     smd.Object,
						},
						{
							Name:     "score",
							Optional: true,
							Ref:      "#/definitions/Score",
							Type:     smd.Object,
						},
					},
					Definitions: map[string]smd.Definition{
						"Candidate": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "handle",
									Type: smd.String,
								},
								{
									Name: "city",
									Type: smd.String,
								},
								{
									Name:     "age",
									Optional: true,
									Type:     smd.Integer,
								},
								{
									Name: "bio",
									Type: smd.String,
								},
								{
									Name: "avatarColor",
									Type: smd.String,
								},
								{
									Name: "initials",
									Type: smd.String,
								},
								{
									Name:     "avatarUrl",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name: "strengths",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "weaknesses",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "currentStageId",
									Type: smd.Integer,
								},
								{
									Name: "createdAt",
									Type: smd.String,
								},
								{
									Name: "updatedAt",
									Type: smd.String,
								},
								{
									Name:     "completedAt",
									Optional: true,
									Type:     smd.String,
								},
							},
						},
						"Score": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "candidateId",
									Type: smd.Integer,
								},
								{
									Name: "stageId",
									Type: smd.Integer,
								},
								{
									Name: "score",
									Type: smd.Integer,
								},
								{
									Name: "scoredAt",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					400: "Validation Error",
					404: "Not Found",
					500: "Internal Error",
				},
			},
			"Rate": {
				Description: `Rate corrects an existing score without changing the candidate's current stage.`,
				Parameters: []smd.JSONSchema{
					{
						Name: "scoreID",
						Type: smd.Integer,
					},
					{
						Name:        "score",
						Description: `int`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `Score`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "Score",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "candidateId",
							Type: smd.Integer,
						},
						{
							Name: "stageId",
							Type: smd.Integer,
						},
						{
							Name: "score",
							Type: smd.Integer,
						},
						{
							Name: "scoredAt",
							Type: smd.String,
						},
					},
				},
				Errors: map[int]string{
					400: "Validation Error",
					404: "Not Found",
					500: "Internal Error",
				},
			},
			"Rollback": {
				Description: `Rollback removes the candidate's most recent score and moves them one stage back.
If the candidate was completed, completedAt is cleared.`,
				Parameters: []smd.JSONSchema{
					{
						Name: "candidateID",
						Type: smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `Candidate`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "Candidate",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "name",
							Type: smd.String,
						},
						{
							Name: "handle",
							Type: smd.String,
						},
						{
							Name: "city",
							Type: smd.String,
						},
						{
							Name:     "age",
							Optional: true,
							Type:     smd.Integer,
						},
						{
							Name: "bio",
							Type: smd.String,
						},
						{
							Name: "avatarColor",
							Type: smd.String,
						},
						{
							Name: "initials",
							Type: smd.String,
						},
						{
							Name:     "avatarUrl",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "strengths",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "weaknesses",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "currentStageId",
							Type: smd.Integer,
						},
						{
							Name: "createdAt",
							Type: smd.String,
						},
						{
							Name: "updatedAt",
							Type: smd.String,
						},
						{
							Name:     "completedAt",
							Optional: true,
							Type:     smd.String,
						},
					},
				},
				Errors: map[int]string{
					400: "Validation Error",
					404: "Not Found",
					500: "Internal Error",
				},
			},
			"Kanban": {
				Description: `Kanban returns candidates grouped by their current stage.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `[]KanbanColumn`,
					Type:        smd.Array,
					TypeName:    "[]KanbanColumn",
					Items: map[string]string{
						"$ref": "#/definitions/KanbanColumn",
					},
					Definitions: map[string]smd.Definition{
						"KanbanColumn": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name:     "stage",
									Optional: true,
									Ref:      "#/definitions/Stage",
									Type:     smd.Object,
								},
								{
									Name: "candidates",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/CandidateSummary",
									},
								},
							},
						},
						"Stage": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "alias",
									Type: smd.String,
								},
								{
									Name: "order",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "shortTitle",
									Type: smd.String,
								},
								{
									Name: "description",
									Type: smd.String,
								},
								{
									Name: "maxScore",
									Type: smd.Integer,
								},
							},
						},
						"CandidateSummary": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "handle",
									Type: smd.String,
								},
								{
									Name: "city",
									Type: smd.String,
								},
								{
									Name:     "age",
									Optional: true,
									Type:     smd.Integer,
								},
								{
									Name: "avatarColor",
									Type: smd.String,
								},
								{
									Name: "initials",
									Type: smd.String,
								},
								{
									Name:     "avatarUrl",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name: "strengths",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "weaknesses",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name:     "currentStage",
									Optional: true,
									Ref:      "#/definitions/Stage",
									Type:     smd.Object,
								},
								{
									Name: "totalPoints",
									Type: smd.Integer,
								},
								{
									Name: "maxPoints",
									Type: smd.Integer,
								},
								{
									Name: "completedStages",
									Type: smd.Integer,
								},
								{
									Name: "stageCount",
									Type: smd.Integer,
								},
								{
									Name:     "completedAt",
									Optional: true,
									Type:     smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					500: "Internal Error",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s CandidateService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.CandidateService.Get:
		var args = struct {
			SortBy CandidateSort `json:"sortBy"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"sortBy"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Get(ctx, args.SortBy))

	case RPC.CandidateService.GetByID:
		var args = struct {
			Id int `json:"id"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"id"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.GetByID(ctx, args.Id))

	case RPC.CandidateService.Add:
		var args = struct {
			Candidate Candidate `json:"candidate"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"candidate"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Add(ctx, args.Candidate))

	case RPC.CandidateService.Update:
		var args = struct {
			Candidate Candidate `json:"candidate"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"candidate"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Update(ctx, args.Candidate))

	case RPC.CandidateService.Delete:
		var args = struct {
			Id int `json:"id"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"id"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Delete(ctx, args.Id))

	case RPC.CandidateService.Advance:
		var args = struct {
			CandidateID int `json:"candidateID"`
			Score       int `json:"score"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"candidateID", "score"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Advance(ctx, args.CandidateID, args.Score))

	case RPC.CandidateService.Rate:
		var args = struct {
			ScoreID int `json:"scoreID"`
			Score   int `json:"score"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"scoreID", "score"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Rate(ctx, args.ScoreID, args.Score))

	case RPC.CandidateService.Rollback:
		var args = struct {
			CandidateID int `json:"candidateID"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"candidateID"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Rollback(ctx, args.CandidateID))

	case RPC.CandidateService.Kanban:
		resp.Set(s.Kanban(ctx))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (DashboardService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Summary": {
				Description: `Summary returns aggregated counters for the page header.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `Summary`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "Summary",
					Properties: smd.PropertyList{
						{
							Name: "candidatesCount",
							Type: smd.Integer,
						},
						{
							Name: "stagesCount",
							Type: smd.Integer,
						},
						{
							Name: "totalPoints",
							Type: smd.Integer,
						},
						{
							Name: "maxPoints",
							Type: smd.Integer,
						},
						{
							Name: "averageOrder",
							Type: smd.Float,
						},
					},
				},
				Errors: map[int]string{
					500: "Internal Error",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s DashboardService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}

	switch method {
	case RPC.DashboardService.Summary:
		resp.Set(s.Summary(ctx))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (StageService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Get": {
				Description: `Get returns all enabled stages ordered by order field.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `[]Stage`,
					Type:        smd.Array,
					TypeName:    "[]Stage",
					Items: map[string]string{
						"$ref": "#/definitions/Stage",
					},
					Definitions: map[string]smd.Definition{
						"Stage": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "alias",
									Type: smd.String,
								},
								{
									Name: "order",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "shortTitle",
									Type: smd.String,
								},
								{
									Name: "description",
									Type: smd.String,
								},
								{
									Name: "maxScore",
									Type: smd.Integer,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					500: "Internal Error",
				},
			},
			"GetByID": {
				Description: `GetByID returns a stage by ID.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "id",
						Description: `int`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `Stage`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "Stage",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "alias",
							Type: smd.String,
						},
						{
							Name: "order",
							Type: smd.Integer,
						},
						{
							Name: "title",
							Type: smd.String,
						},
						{
							Name: "shortTitle",
							Type: smd.String,
						},
						{
							Name: "description",
							Type: smd.String,
						},
						{
							Name: "maxScore",
							Type: smd.Integer,
						},
					},
				},
				Errors: map[int]string{
					404: "Not Found",
					500: "Internal Error",
				},
			},
			"Add": {
				Description: `Add creates a new stage.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "stage",
						Description: `Stage`,
						Type:        smd.Object,
						TypeName:    "Stage",
						Properties: smd.PropertyList{
							{
								Name: "id",
								Type: smd.Integer,
							},
							{
								Name: "alias",
								Type: smd.String,
							},
							{
								Name: "order",
								Type: smd.Integer,
							},
							{
								Name: "title",
								Type: smd.String,
							},
							{
								Name: "shortTitle",
								Type: smd.String,
							},
							{
								Name: "description",
								Type: smd.String,
							},
							{
								Name: "maxScore",
								Type: smd.Integer,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `Stage`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "Stage",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "alias",
							Type: smd.String,
						},
						{
							Name: "order",
							Type: smd.Integer,
						},
						{
							Name: "title",
							Type: smd.String,
						},
						{
							Name: "shortTitle",
							Type: smd.String,
						},
						{
							Name: "description",
							Type: smd.String,
						},
						{
							Name: "maxScore",
							Type: smd.Integer,
						},
					},
				},
				Errors: map[int]string{
					400: "Validation Error",
					500: "Internal Error",
				},
			},
			"Update": {
				Description: `Update changes a stage. To reorder use Reorder.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "stage",
						Description: `Stage`,
						Type:        smd.Object,
						TypeName:    "Stage",
						Properties: smd.PropertyList{
							{
								Name: "id",
								Type: smd.Integer,
							},
							{
								Name: "alias",
								Type: smd.String,
							},
							{
								Name: "order",
								Type: smd.Integer,
							},
							{
								Name: "title",
								Type: smd.String,
							},
							{
								Name: "shortTitle",
								Type: smd.String,
							},
							{
								Name: "description",
								Type: smd.String,
							},
							{
								Name: "maxScore",
								Type: smd.Integer,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
				Errors: map[int]string{
					404: "Not Found",
					400: "Validation Error",
					500: "Internal Error",
				},
			},
			"Delete": {
				Description: `Delete removes a stage. Fails if any candidate has a score for it.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "id",
						Description: `int`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
				Errors: map[int]string{
					404: "Not Found",
					400: "stage has scores",
					500: "Internal Error",
				},
			},
			"Reorder": {
				Description: `Reorder accepts an ordered list of stage ids and re-numbers order to match.
All enabled stages must be present, no duplicates allowed.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "ids",
						Description: `[]int`,
						Type:        smd.Array,
						TypeName:    "[]",
						Items: map[string]string{
							"type": smd.Integer,
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `[]Stage`,
					Type:        smd.Array,
					TypeName:    "[]Stage",
					Items: map[string]string{
						"$ref": "#/definitions/Stage",
					},
					Definitions: map[string]smd.Definition{
						"Stage": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "alias",
									Type: smd.String,
								},
								{
									Name: "order",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "shortTitle",
									Type: smd.String,
								},
								{
									Name: "description",
									Type: smd.String,
								},
								{
									Name: "maxScore",
									Type: smd.Integer,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					400: "Validation Error",
					500: "Internal Error",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s StageService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.StageService.Get:
		resp.Set(s.Get(ctx))

	case RPC.StageService.GetByID:
		var args = struct {
			Id int `json:"id"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"id"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.GetByID(ctx, args.Id))

	case RPC.StageService.Add:
		var args = struct {
			Stage Stage `json:"stage"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"stage"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Add(ctx, args.Stage))

	case RPC.StageService.Update:
		var args = struct {
			Stage Stage `json:"stage"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"stage"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Update(ctx, args.Stage))

	case RPC.StageService.Delete:
		var args = struct {
			Id int `json:"id"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"id"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Delete(ctx, args.Id))

	case RPC.StageService.Reorder:
		var args = struct {
			Ids []int `json:"ids"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"ids"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Reorder(ctx, args.Ids))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
