// Code generated by zenrpc v2.3.1; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	AuthService      struct{ Login, Me, Register string }
	CandidateService struct{ Get, GetByID, Add, Update, Delete, Advance, Rate, Rollback, SetLink, SetAvatarURL, Kanban string }
	DashboardService struct{ Summary string }
	StageService     struct{ Get, GetByID, Add, Update, Delete, Reorder string }
}{
	AuthService: struct{ Login, Me, Register string }{
		Login:    "login",
		Me:       "me",
		Register: "register",
	},
	CandidateService: struct{ Get, GetByID, Add, Update, Delete, Advance, Rate, Rollback, SetLink, SetAvatarURL, Kanban string }{
		Get:          "get",
		GetByID:      "getbyid",
		Add:          "add",
		Update:       "update",
		Delete:       "delete",
		Advance:      "advance",
		Rate:         "rate",
		Rollback:     "rollback",
		SetLink:      "setlink",
		SetAvatarURL: "setavatarurl",
		Kanban:       "kanban",
	},
	DashboardService: struct{ Summary string }{
		Summary: "summary",
	},
	StageService: struct{ Get, GetByID, Add, Update, Delete, Reorder string }{
		Get:     "get",
		GetByID: "getbyid",
		Add:     "add",
		Update:  "update",
		Delete:  "delete",
		Reorder: "reorder",
	},
}

func (AuthService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Login": {
				Description: `Login authenticates an existing admin or candidate and returns a fresh authKey.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "login",
						Description: `User login`,
						Type:        smd.String,
					},
					{
						Name:        "password",
						Description: `User password`,
						Type:        smd.String,
					},
					{
						Name:        "userType",
						Description: `User type ("admin" or "user")`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `User authentication key`,
					Type:        smd.String,
				},
				Errors: map[int]string{
					400: "Validation Error",
					500: "Internal Error",
				},
			},
			"Me": {
				Description: `Me returns the current principal — login, userId and userType (admin or
candidate). Requires the Authorization2 header; the middleware resolves
admin first, then candidate.`,
				Parameters: []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `Me current principal`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "Me",
					Properties: smd.PropertyList{
						{
							Name: "userId",
							Type: smd.Integer,
						},
						{
							Name: "login",
							Type: smd.String,
						},
						{
							Name: "userType",
							Type: smd.String,
						},
					},
				},
				Errors: map[int]string{
					401: "Unauthorized",
					500: "Internal Error",
				},
			},
			"Register": {
				Description: `Register creates a candidate and returns a fresh authKey (userType=user only).`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "login",
						Description: `User login`,
						Type:        smd.String,
					},
					{
						Name:        "password",
						Description: `User password`,
						Type:        smd.String,
					},
					{
						Name:        "userType",
						Description: `User type ("user" only)`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `User authentication key`,
					Type:        smd.String,
				},
				Errors: map[int]string{
					400: "Validation Error",
					500: "Internal Error",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s AuthService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.AuthService.Login:
		var args = struct {
			Login    string `json:"login"`
			Password string `json:"password"`
			UserType string `json:"userType"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"login", "password", "userType"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Login(ctx, args.Login, args.Password, args.UserType))

	case RPC.AuthService.Me:
		resp.Set(s.Me(ctx))

	case RPC.AuthService.Register:
		var args = struct {
			Login    string `json:"login"`
			Password string `json:"password"`
			UserType string `json:"userType"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"login", "password", "userType"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Register(ctx, args.Login, args.Password, args.UserType))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (CandidateService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Get": {
				Description: `Get returns candidate list with aggregates, sorted by sortBy.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "sortBy",
						Description: `CandidateSort`,
						Type:        smd.Object,
						TypeName:    "CandidateSort",
						Properties:  smd.PropertyList{},
					},
				},
				Returns: smd.JSONSchema{
					Description: `[]CandidateSummary`,
					Type:        smd.Array,
					TypeName:    "[]CandidateSummary",
					Items: map[string]string{
						"$ref": "#/definitions/CandidateSummary",
					},
					Definitions: map[string]smd.Definition{
						"CandidateSummary": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "handle",
									Type: smd.String,
								},
								{
									Name: "city",
									Type: smd.String,
								},
								{
									Name:     "age",
									Optional: true,
									Type:     smd.Integer,
								},
								{
									Name: "avatarColor",
									Type: smd.String,
								},
								{
									Name: "initials",
									Type: smd.String,
								},
								{
									Name:     "avatarUrl",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name: "strengths",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "weaknesses",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name:     "currentStage",
									Optional: true,
									Ref:      "#/definitions/Stage",
									Type:     smd.Object,
								},
								{
									Name:     "currentCandidateStage",
									Optional: true,
									Ref:      "#/definitions/CandidateStageSummary",
									Type:     smd.Object,
								},
								{
									Name: "totalPoints",
									Type: smd.Integer,
								},
								{
									Name: "maxPoints",
									Type: smd.Integer,
								},
								{
									Name: "completedStages",
									Type: smd.Integer,
								},
								{
									Name: "stageCount",
									Type: smd.Integer,
								},
								{
									Name:     "completedAt",
									Optional: true,
									Type:     smd.String,
								},
							},
						},
						"Stage": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "alias",
									Type: smd.String,
								},
								{
									Name: "order",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "shortTitle",
									Type: smd.String,
								},
								{
									Name: "description",
									Type: smd.String,
								},
								{
									Name: "maxScore",
									Type: smd.Integer,
								},
								{
									Name: "deadlineDays",
									Type: smd.Integer,
								},
							},
						},
						"CandidateStageSummary": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name:     "link",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name:     "deadline",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name: "createdAt",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					500: "Internal Error",
				},
			},
			"GetByID": {
				Description: `GetByID returns full candidate detail with stage history.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "id",
						Description: `int`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `CandidateDetail`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "CandidateDetail",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "name",
							Type: smd.String,
						},
						{
							Name: "handle",
							Type: smd.String,
						},
						{
							Name: "city",
							Type: smd.String,
						},
						{
							Name:     "age",
							Optional: true,
							Type:     smd.Integer,
						},
						{
							Name: "avatarColor",
							Type: smd.String,
						},
						{
							Name: "initials",
							Type: smd.String,
						},
						{
							Name:     "avatarUrl",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "strengths",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "weaknesses",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name:     "currentStage",
							Optional: true,
							Ref:      "#/definitions/Stage",
							Type:     smd.Object,
						},
						{
							Name:     "currentCandidateStage",
							Optional: true,
							Ref:      "#/definitions/CandidateStageSummary",
							Type:     smd.Object,
						},
						{
							Name: "totalPoints",
							Type: smd.Integer,
						},
						{
							Name: "maxPoints",
							Type: smd.Integer,
						},
						{
							Name: "completedStages",
							Type: smd.Integer,
						},
						{
							Name: "stageCount",
							Type: smd.Integer,
						},
						{
							Name:     "completedAt",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "bio",
							Type: smd.String,
						},
						{
							Name: "history",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/CandidateStageHistory",
							},
						},
					},
					Definitions: map[string]smd.Definition{
						"Stage": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "alias",
									Type: smd.String,
								},
								{
									Name: "order",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "shortTitle",
									Type: smd.String,
								},
								{
									Name: "description",
									Type: smd.String,
								},
								{
									Name: "maxScore",
									Type: smd.Integer,
								},
								{
									Name: "deadlineDays",
									Type: smd.Integer,
								},
							},
						},
						"CandidateStageSummary": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name:     "link",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name:     "deadline",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name: "createdAt",
									Type: smd.String,
								},
							},
						},
						"CandidateStageHistory": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "stageId",
									Type: smd.Integer,
								},
								{
									Name:     "stage",
									Optional: true,
									Ref:      "#/definitions/Stage",
									Type:     smd.Object,
								},
								{
									Name: "status",
									Type: smd.String,
								},
								{
									Name:     "score",
									Optional: true,
									Type:     smd.Integer,
								},
								{
									Name: "maxScore",
									Type: smd.Integer,
								},
								{
									Name:     "scoredAt",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name:     "candidateStageId",
									Optional: true,
									Type:     smd.Integer,
								},
								{
									Name:     "link",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name:     "deadline",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name:     "createdAt",
									Optional: true,
									Type:     smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					404: "Not Found",
					500: "Internal Error",
				},
			},
			"Add": {
				Description: `Add creates a candidate and returns a one-time password (only here).`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "candidate",
						Description: `Candidate`,
						Type:        smd.Object,
						TypeName:    "Candidate",
						Properties: smd.PropertyList{
							{
								Name: "id",
								Type: smd.Integer,
							},
							{
								Name: "name",
								Type: smd.String,
							},
							{
								Name: "handle",
								Type: smd.String,
							},
							{
								Name: "login",
								Type: smd.String,
							},
							{
								Name: "city",
								Type: smd.String,
							},
							{
								Name:     "age",
								Optional: true,
								Type:     smd.Integer,
							},
							{
								Name: "bio",
								Type: smd.String,
							},
							{
								Name: "avatarColor",
								Type: smd.String,
							},
							{
								Name: "initials",
								Type: smd.String,
							},
							{
								Name:     "avatarUrl",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name: "strengths",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "weaknesses",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "currentStageId",
								Type: smd.Integer,
							},
							{
								Name: "createdAt",
								Type: smd.String,
							},
							{
								Name: "updatedAt",
								Type: smd.String,
							},
							{
								Name:     "completedAt",
								Optional: true,
								Type:     smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `CandidateWithPassword`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "CandidateWithPassword",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "name",
							Type: smd.String,
						},
						{
							Name: "handle",
							Type: smd.String,
						},
						{
							Name: "login",
							Type: smd.String,
						},
						{
							Name: "city",
							Type: smd.String,
						},
						{
							Name:     "age",
							Optional: true,
							Type:     smd.Integer,
						},
						{
							Name: "bio",
							Type: smd.String,
						},
						{
							Name: "avatarColor",
							Type: smd.String,
						},
						{
							Name: "initials",
							Type: smd.String,
						},
						{
							Name:     "avatarUrl",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "strengths",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "weaknesses",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "currentStageId",
							Type: smd.Integer,
						},
						{
							Name: "createdAt",
							Type: smd.String,
						},
						{
							Name: "updatedAt",
							Type: smd.String,
						},
						{
							Name:     "completedAt",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "password",
							Type: smd.String,
						},
					},
				},
				Errors: map[int]string{
					400: "Validation Error",
					500: "Internal Error",
				},
			},
			"Update": {
				Description: `Update changes basic fields. login/currentStageId/timestamps are immutable here.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "candidate",
						Description: `Candidate`,
						Type:        smd.Object,
						TypeName:    "Candidate",
						Properties: smd.PropertyList{
							{
								Name: "id",
								Type: smd.Integer,
							},
							{
								Name: "name",
								Type: smd.String,
							},
							{
								Name: "handle",
								Type: smd.String,
							},
							{
								Name: "login",
								Type: smd.String,
							},
							{
								Name: "city",
								Type: smd.String,
							},
							{
								Name:     "age",
								Optional: true,
								Type:     smd.Integer,
							},
							{
								Name: "bio",
								Type: smd.String,
							},
							{
								Name: "avatarColor",
								Type: smd.String,
							},
							{
								Name: "initials",
								Type: smd.String,
							},
							{
								Name:     "avatarUrl",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name: "strengths",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "weaknesses",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.String,
								},
							},
							{
								Name: "currentStageId",
								Type: smd.Integer,
							},
							{
								Name: "createdAt",
								Type: smd.String,
							},
							{
								Name: "updatedAt",
								Type: smd.String,
							},
							{
								Name:     "completedAt",
								Optional: true,
								Type:     smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
				Errors: map[int]string{
					404: "Not Found",
					400: "Validation Error",
					500: "Internal Error",
				},
			},
			"Delete": {
				Description: `Delete soft-deletes a candidate.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "id",
						Description: `int`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
				Errors: map[int]string{
					404: "Not Found",
					500: "Internal Error",
				},
			},
			"Advance": {
				Description: `Advance scores current stage; moves to next or sets completedAt if last.`,
				Parameters: []smd.JSONSchema{
					{
						Name: "candidateID",
						Type: smd.Integer,
					},
					{
						Name:        "score",
						Description: `int`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `AdvanceResult`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "AdvanceResult",
					Properties: smd.PropertyList{
						{
							Name:     "candidate",
							Optional: true,
							Ref:      "#/definitions/Candidate",
							Type:     smd.Object,
						},
						{
							Name:     "candidateStage",
							Optional: true,
							Ref:      "#/definitions/CandidateStage",
							Type:     smd.Object,
						},
					},
					Definitions: map[string]smd.Definition{
						"Candidate": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "handle",
									Type: smd.String,
								},
								{
									Name: "login",
									Type: smd.String,
								},
								{
									Name: "city",
									Type: smd.String,
								},
								{
									Name:     "age",
									Optional: true,
									Type:     smd.Integer,
								},
								{
									Name: "bio",
									Type: smd.String,
								},
								{
									Name: "avatarColor",
									Type: smd.String,
								},
								{
									Name: "initials",
									Type: smd.String,
								},
								{
									Name:     "avatarUrl",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name: "strengths",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "weaknesses",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "currentStageId",
									Type: smd.Integer,
								},
								{
									Name: "createdAt",
									Type: smd.String,
								},
								{
									Name: "updatedAt",
									Type: smd.String,
								},
								{
									Name:     "completedAt",
									Optional: true,
									Type:     smd.String,
								},
							},
						},
						"CandidateStage": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "candidateId",
									Type: smd.Integer,
								},
								{
									Name: "stageId",
									Type: smd.Integer,
								},
								{
									Name:     "link",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name:     "score",
									Optional: true,
									Type:     smd.Integer,
								},
								{
									Name:     "scoredAt",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name:     "deadline",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name: "createdAt",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					400: "Validation Error",
					404: "Not Found",
					500: "Internal Error",
				},
			},
			"Rate": {
				Description: `Rate sets or corrects score on a CandidateStage; does not move stage.`,
				Parameters: []smd.JSONSchema{
					{
						Name: "candidateStageID",
						Type: smd.Integer,
					},
					{
						Name:        "score",
						Description: `int`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `CandidateStage`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "CandidateStage",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "candidateId",
							Type: smd.Integer,
						},
						{
							Name: "stageId",
							Type: smd.Integer,
						},
						{
							Name:     "link",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name:     "score",
							Optional: true,
							Type:     smd.Integer,
						},
						{
							Name:     "scoredAt",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name:     "deadline",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "createdAt",
							Type: smd.String,
						},
					},
				},
				Errors: map[int]string{
					400: "Validation Error",
					404: "Not Found",
					500: "Internal Error",
				},
			},
			"Rollback": {
				Description: `Rollback reverts the most recent Advance; clears completedAt if set.`,
				Parameters: []smd.JSONSchema{
					{
						Name: "candidateID",
						Type: smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `Candidate`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "Candidate",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "name",
							Type: smd.String,
						},
						{
							Name: "handle",
							Type: smd.String,
						},
						{
							Name: "login",
							Type: smd.String,
						},
						{
							Name: "city",
							Type: smd.String,
						},
						{
							Name:     "age",
							Optional: true,
							Type:     smd.Integer,
						},
						{
							Name: "bio",
							Type: smd.String,
						},
						{
							Name: "avatarColor",
							Type: smd.String,
						},
						{
							Name: "initials",
							Type: smd.String,
						},
						{
							Name:     "avatarUrl",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "strengths",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "weaknesses",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "currentStageId",
							Type: smd.Integer,
						},
						{
							Name: "createdAt",
							Type: smd.String,
						},
						{
							Name: "updatedAt",
							Type: smd.String,
						},
						{
							Name:     "completedAt",
							Optional: true,
							Type:     smd.String,
						},
					},
				},
				Errors: map[int]string{
					400: "Validation Error",
					404: "Not Found",
					500: "Internal Error",
				},
			},
			"SetLink": {
				Description: `SetLink attaches or detaches link on a CandidateStage (admin or self-candidate).`,
				Parameters: []smd.JSONSchema{
					{
						Name: "candidateStageID",
						Type: smd.Integer,
					},
					{
						Name:        "link",
						Optional:    true,
						Description: `*string`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `CandidateStage`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "CandidateStage",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "candidateId",
							Type: smd.Integer,
						},
						{
							Name: "stageId",
							Type: smd.Integer,
						},
						{
							Name:     "link",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name:     "score",
							Optional: true,
							Type:     smd.Integer,
						},
						{
							Name:     "scoredAt",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name:     "deadline",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "createdAt",
							Type: smd.String,
						},
					},
				},
				Errors: map[int]string{
					401: "Unauthorized",
					403: "Forbidden",
					404: "Not Found",
					400: "Validation Error",
					500: "Internal Error",
				},
			},
			"SetAvatarURL": {
				Description: `SetAvatarURL attaches or detaches avatarUrl on a Candidate (admin or self-candidate).`,
				Parameters: []smd.JSONSchema{
					{
						Name: "candidateID",
						Type: smd.Integer,
					},
					{
						Name:        "avatarUrl",
						Optional:    true,
						Description: `*string`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `Candidate`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "Candidate",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "name",
							Type: smd.String,
						},
						{
							Name: "handle",
							Type: smd.String,
						},
						{
							Name: "login",
							Type: smd.String,
						},
						{
							Name: "city",
							Type: smd.String,
						},
						{
							Name:     "age",
							Optional: true,
							Type:     smd.Integer,
						},
						{
							Name: "bio",
							Type: smd.String,
						},
						{
							Name: "avatarColor",
							Type: smd.String,
						},
						{
							Name: "initials",
							Type: smd.String,
						},
						{
							Name:     "avatarUrl",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "strengths",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "weaknesses",
							Type: smd.Array,
							Items: map[string]string{
								"type": smd.String,
							},
						},
						{
							Name: "currentStageId",
							Type: smd.Integer,
						},
						{
							Name: "createdAt",
							Type: smd.String,
						},
						{
							Name: "updatedAt",
							Type: smd.String,
						},
						{
							Name:     "completedAt",
							Optional: true,
							Type:     smd.String,
						},
					},
				},
				Errors: map[int]string{
					401: "Unauthorized",
					403: "Forbidden",
					404: "Not Found",
					400: "Validation Error",
					500: "Internal Error",
				},
			},
			"Kanban": {
				Description: `Kanban returns candidates grouped by their current stage.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `[]KanbanColumn`,
					Type:        smd.Array,
					TypeName:    "[]KanbanColumn",
					Items: map[string]string{
						"$ref": "#/definitions/KanbanColumn",
					},
					Definitions: map[string]smd.Definition{
						"KanbanColumn": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name:     "stage",
									Optional: true,
									Ref:      "#/definitions/Stage",
									Type:     smd.Object,
								},
								{
									Name: "candidates",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/CandidateSummary",
									},
								},
							},
						},
						"Stage": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "alias",
									Type: smd.String,
								},
								{
									Name: "order",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "shortTitle",
									Type: smd.String,
								},
								{
									Name: "description",
									Type: smd.String,
								},
								{
									Name: "maxScore",
									Type: smd.Integer,
								},
								{
									Name: "deadlineDays",
									Type: smd.Integer,
								},
							},
						},
						"CandidateSummary": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "handle",
									Type: smd.String,
								},
								{
									Name: "city",
									Type: smd.String,
								},
								{
									Name:     "age",
									Optional: true,
									Type:     smd.Integer,
								},
								{
									Name: "avatarColor",
									Type: smd.String,
								},
								{
									Name: "initials",
									Type: smd.String,
								},
								{
									Name:     "avatarUrl",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name: "strengths",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "weaknesses",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name:     "currentStage",
									Optional: true,
									Ref:      "#/definitions/Stage",
									Type:     smd.Object,
								},
								{
									Name:     "currentCandidateStage",
									Optional: true,
									Ref:      "#/definitions/CandidateStageSummary",
									Type:     smd.Object,
								},
								{
									Name: "totalPoints",
									Type: smd.Integer,
								},
								{
									Name: "maxPoints",
									Type: smd.Integer,
								},
								{
									Name: "completedStages",
									Type: smd.Integer,
								},
								{
									Name: "stageCount",
									Type: smd.Integer,
								},
								{
									Name:     "completedAt",
									Optional: true,
									Type:     smd.String,
								},
							},
						},
						"CandidateStageSummary": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name:     "link",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name:     "deadline",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name: "createdAt",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					500: "Internal Error",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s CandidateService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.CandidateService.Get:
		var args = struct {
			SortBy CandidateSort `json:"sortBy"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"sortBy"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Get(ctx, args.SortBy))

	case RPC.CandidateService.GetByID:
		var args = struct {
			Id int `json:"id"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"id"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.GetByID(ctx, args.Id))

	case RPC.CandidateService.Add:
		var args = struct {
			Candidate Candidate `json:"candidate"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"candidate"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Add(ctx, args.Candidate))

	case RPC.CandidateService.Update:
		var args = struct {
			Candidate Candidate `json:"candidate"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"candidate"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Update(ctx, args.Candidate))

	case RPC.CandidateService.Delete:
		var args = struct {
			Id int `json:"id"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"id"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Delete(ctx, args.Id))

	case RPC.CandidateService.Advance:
		var args = struct {
			CandidateID int `json:"candidateID"`
			Score       int `json:"score"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"candidateID", "score"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Advance(ctx, args.CandidateID, args.Score))

	case RPC.CandidateService.Rate:
		var args = struct {
			CandidateStageID int `json:"candidateStageID"`
			Score            int `json:"score"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"candidateStageID", "score"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Rate(ctx, args.CandidateStageID, args.Score))

	case RPC.CandidateService.Rollback:
		var args = struct {
			CandidateID int `json:"candidateID"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"candidateID"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Rollback(ctx, args.CandidateID))

	case RPC.CandidateService.SetLink:
		var args = struct {
			CandidateStageID int     `json:"candidateStageID"`
			Link             *string `json:"link"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"candidateStageID", "link"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.SetLink(ctx, args.CandidateStageID, args.Link))

	case RPC.CandidateService.SetAvatarURL:
		var args = struct {
			CandidateID int     `json:"candidateID"`
			AvatarUrl   *string `json:"avatarUrl"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"candidateID", "avatarUrl"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.SetAvatarURL(ctx, args.CandidateID, args.AvatarUrl))

	case RPC.CandidateService.Kanban:
		resp.Set(s.Kanban(ctx))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (DashboardService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Summary": {
				Description: `Summary returns aggregated counters for the page header.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `Summary`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "Summary",
					Properties: smd.PropertyList{
						{
							Name: "candidatesCount",
							Type: smd.Integer,
						},
						{
							Name: "stagesCount",
							Type: smd.Integer,
						},
						{
							Name: "totalPoints",
							Type: smd.Integer,
						},
						{
							Name: "maxPoints",
							Type: smd.Integer,
						},
						{
							Name: "averageOrder",
							Type: smd.Float,
						},
					},
				},
				Errors: map[int]string{
					500: "Internal Error",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s DashboardService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}

	switch method {
	case RPC.DashboardService.Summary:
		resp.Set(s.Summary(ctx))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}

func (StageService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"Get": {
				Description: `Get returns all enabled stages ordered by order field.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Description: `[]Stage`,
					Type:        smd.Array,
					TypeName:    "[]Stage",
					Items: map[string]string{
						"$ref": "#/definitions/Stage",
					},
					Definitions: map[string]smd.Definition{
						"Stage": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "alias",
									Type: smd.String,
								},
								{
									Name: "order",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "shortTitle",
									Type: smd.String,
								},
								{
									Name: "description",
									Type: smd.String,
								},
								{
									Name: "maxScore",
									Type: smd.Integer,
								},
								{
									Name: "deadlineDays",
									Type: smd.Integer,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					500: "Internal Error",
				},
			},
			"GetByID": {
				Description: `GetByID returns a stage by ID.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "id",
						Description: `int`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `Stage`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "Stage",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "alias",
							Type: smd.String,
						},
						{
							Name: "order",
							Type: smd.Integer,
						},
						{
							Name: "title",
							Type: smd.String,
						},
						{
							Name: "shortTitle",
							Type: smd.String,
						},
						{
							Name: "description",
							Type: smd.String,
						},
						{
							Name: "maxScore",
							Type: smd.Integer,
						},
						{
							Name: "deadlineDays",
							Type: smd.Integer,
						},
					},
				},
				Errors: map[int]string{
					404: "Not Found",
					500: "Internal Error",
				},
			},
			"Add": {
				Description: `Add creates a new stage.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "stage",
						Description: `Stage`,
						Type:        smd.Object,
						TypeName:    "Stage",
						Properties: smd.PropertyList{
							{
								Name: "id",
								Type: smd.Integer,
							},
							{
								Name: "alias",
								Type: smd.String,
							},
							{
								Name: "order",
								Type: smd.Integer,
							},
							{
								Name: "title",
								Type: smd.String,
							},
							{
								Name: "shortTitle",
								Type: smd.String,
							},
							{
								Name: "description",
								Type: smd.String,
							},
							{
								Name: "maxScore",
								Type: smd.Integer,
							},
							{
								Name: "deadlineDays",
								Type: smd.Integer,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `Stage`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "Stage",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "alias",
							Type: smd.String,
						},
						{
							Name: "order",
							Type: smd.Integer,
						},
						{
							Name: "title",
							Type: smd.String,
						},
						{
							Name: "shortTitle",
							Type: smd.String,
						},
						{
							Name: "description",
							Type: smd.String,
						},
						{
							Name: "maxScore",
							Type: smd.Integer,
						},
						{
							Name: "deadlineDays",
							Type: smd.Integer,
						},
					},
				},
				Errors: map[int]string{
					400: "Validation Error",
					500: "Internal Error",
				},
			},
			"Update": {
				Description: `Update changes a stage. To reorder use Reorder.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "stage",
						Description: `Stage`,
						Type:        smd.Object,
						TypeName:    "Stage",
						Properties: smd.PropertyList{
							{
								Name: "id",
								Type: smd.Integer,
							},
							{
								Name: "alias",
								Type: smd.String,
							},
							{
								Name: "order",
								Type: smd.Integer,
							},
							{
								Name: "title",
								Type: smd.String,
							},
							{
								Name: "shortTitle",
								Type: smd.String,
							},
							{
								Name: "description",
								Type: smd.String,
							},
							{
								Name: "maxScore",
								Type: smd.Integer,
							},
							{
								Name: "deadlineDays",
								Type: smd.Integer,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
				Errors: map[int]string{
					404: "Not Found",
					400: "Validation Error",
					500: "Internal Error",
				},
			},
			"Delete": {
				Description: `Delete removes a stage. Fails if any candidate has a score for it.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "id",
						Description: `int`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `bool`,
					Type:        smd.Boolean,
				},
				Errors: map[int]string{
					404: "Not Found",
					400: "stage has scores",
					500: "Internal Error",
				},
			},
			"Reorder": {
				Description: `Reorder accepts an ordered list of stage ids and re-numbers order to match.
All enabled stages must be present, no duplicates allowed.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "ids",
						Description: `[]int`,
						Type:        smd.Array,
						TypeName:    "[]",
						Items: map[string]string{
							"type": smd.Integer,
						},
					},
				},
				Returns: smd.JSONSchema{
					Description: `[]Stage`,
					Type:        smd.Array,
					TypeName:    "[]Stage",
					Items: map[string]string{
						"$ref": "#/definitions/Stage",
					},
					Definitions: map[string]smd.Definition{
						"Stage": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "alias",
									Type: smd.String,
								},
								{
									Name: "order",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "shortTitle",
									Type: smd.String,
								},
								{
									Name: "description",
									Type: smd.String,
								},
								{
									Name: "maxScore",
									Type: smd.Integer,
								},
								{
									Name: "deadlineDays",
									Type: smd.Integer,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					400: "Validation Error",
					500: "Internal Error",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s StageService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.StageService.Get:
		resp.Set(s.Get(ctx))

	case RPC.StageService.GetByID:
		var args = struct {
			Id int `json:"id"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"id"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.GetByID(ctx, args.Id))

	case RPC.StageService.Add:
		var args = struct {
			Stage Stage `json:"stage"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"stage"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Add(ctx, args.Stage))

	case RPC.StageService.Update:
		var args = struct {
			Stage Stage `json:"stage"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"stage"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Update(ctx, args.Stage))

	case RPC.StageService.Delete:
		var args = struct {
			Id int `json:"id"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"id"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Delete(ctx, args.Id))

	case RPC.StageService.Reorder:
		var args = struct {
			Ids []int `json:"ids"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"ids"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Reorder(ctx, args.Ids))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
